ALTER TABLE `finances` ADD `userName` text;--> statement-breakpoint
ALTER TABLE `inventory_transactions` ADD `productName` text;--> statement-breakpoint
ALTER TABLE `inventory_transactions` ADD `productBarcode` text;--> statement-breakpoint
ALTER TABLE `inventory_transactions` ADD `productCategory` text;--> statement-breakpoint
ALTER TABLE `inventory_transactions` ADD `productBrand` text;--> statement-breakpoint
ALTER TABLE `inventory_transactions` ADD `productUnit` text;--> statement-breakpoint
ALTER TABLE `inventory_transactions` ADD `variantName` text;--> statement-breakpoint
ALTER TABLE `inventory_transactions` ADD `variantCode` text;--> statement-breakpoint
ALTER TABLE `inventory_transactions` ADD `variantNetto` real;--> statement-breakpoint
ALTER TABLE `inventory_transactions` ADD `contextName` text;--> statement-breakpoint
ALTER TABLE `payable_realizations` ADD `paymentMethodName` text;--> statement-breakpoint
ALTER TABLE `payables` ADD `supplierPhone` text;--> statement-breakpoint
ALTER TABLE `payables` ADD `supplierAddress` text;--> statement-breakpoint
ALTER TABLE `purchase_items` ADD `productName` text;--> statement-breakpoint
ALTER TABLE `purchase_items` ADD `productBarcode` text;--> statement-breakpoint
ALTER TABLE `purchase_items` ADD `productCategory` text;--> statement-breakpoint
ALTER TABLE `purchase_items` ADD `productBrand` text;--> statement-breakpoint
ALTER TABLE `purchase_items` ADD `productUnit` text;--> statement-breakpoint
ALTER TABLE `purchase_items` ADD `variantName` text;--> statement-breakpoint
ALTER TABLE `purchase_items` ADD `variantCode` text;--> statement-breakpoint
ALTER TABLE `purchase_items` ADD `variantNetto` real;--> statement-breakpoint
ALTER TABLE `purchase_items` ADD `note` text;--> statement-breakpoint
ALTER TABLE `purchase_return_items` ADD `productName` text;--> statement-breakpoint
ALTER TABLE `purchase_return_items` ADD `productBarcode` text;--> statement-breakpoint
ALTER TABLE `purchase_return_items` ADD `productCategory` text;--> statement-breakpoint
ALTER TABLE `purchase_return_items` ADD `productBrand` text;--> statement-breakpoint
ALTER TABLE `purchase_return_items` ADD `productUnit` text;--> statement-breakpoint
ALTER TABLE `purchase_return_items` ADD `variantId` text;--> statement-breakpoint
ALTER TABLE `purchase_return_items` ADD `variantName` text;--> statement-breakpoint
ALTER TABLE `purchase_return_items` ADD `variantCode` text;--> statement-breakpoint
ALTER TABLE `purchase_return_items` ADD `variantNetto` real;--> statement-breakpoint
ALTER TABLE `purchase_return_items` ADD `note` text;--> statement-breakpoint
ALTER TABLE `purchase_returns` ADD `supplierPhone` text;--> statement-breakpoint
ALTER TABLE `purchase_returns` ADD `supplierAddress` text;--> statement-breakpoint
ALTER TABLE `purchases` ADD `supplierPhone` text;--> statement-breakpoint
ALTER TABLE `purchases` ADD `supplierAddress` text;--> statement-breakpoint
ALTER TABLE `purchases` ADD `employeeId` text;--> statement-breakpoint
ALTER TABLE `purchases` ADD `employeeName` text;--> statement-breakpoint
ALTER TABLE `purchases` ADD `paymentTypeCommission` real DEFAULT 0;--> statement-breakpoint
ALTER TABLE `purchases` ADD `paymentTypeCommissionType` text DEFAULT 'PERCENTAGE';--> statement-breakpoint
ALTER TABLE `purchases` ADD `paymentTypeMinimalAmount` real DEFAULT 0;--> statement-breakpoint
ALTER TABLE `purchases` DROP COLUMN `paymentType`;--> statement-breakpoint
ALTER TABLE `purchases` DROP COLUMN `paymentTypeId`;--> statement-breakpoint
ALTER TABLE `receivable_realizations` ADD `paymentMethodName` text;--> statement-breakpoint
ALTER TABLE `receivables` ADD `userName` text;--> statement-breakpoint
ALTER TABLE `receivables` ADD `customerPhone` text;--> statement-breakpoint
ALTER TABLE `receivables` ADD `customerAddress` text;--> statement-breakpoint
ALTER TABLE `receivables` ADD `transactionLocalRefId` text;--> statement-breakpoint
ALTER TABLE `receivables` ADD `transactionTotalAmount` real;--> statement-breakpoint
ALTER TABLE `shifts` ADD `cashDrawerName` text;--> statement-breakpoint
ALTER TABLE `shifts` ADD `userName` text;--> statement-breakpoint
ALTER TABLE `stock_opname_items` ADD `productName` text;--> statement-breakpoint
ALTER TABLE `stock_opname_items` ADD `productBarcode` text;--> statement-breakpoint
ALTER TABLE `stock_opname_items` ADD `productCategory` text;--> statement-breakpoint
ALTER TABLE `stock_opname_items` ADD `productBrand` text;--> statement-breakpoint
ALTER TABLE `stock_opname_items` ADD `productUnit` text;--> statement-breakpoint
ALTER TABLE `stock_opname_items` ADD `variantName` text;--> statement-breakpoint
ALTER TABLE `stock_opname_items` ADD `variantCode` text;--> statement-breakpoint
ALTER TABLE `stock_opname_items` ADD `variantNetto` real;--> statement-breakpoint
ALTER TABLE `stock_opnames` ADD `createdByName` text;--> statement-breakpoint
ALTER TABLE `store_supplies` ADD `createdByName` text;--> statement-breakpoint
ALTER TABLE `store_supply_items` ADD `productName` text;--> statement-breakpoint
ALTER TABLE `store_supply_items` ADD `productBarcode` text;--> statement-breakpoint
ALTER TABLE `store_supply_items` ADD `productCategory` text;--> statement-breakpoint
ALTER TABLE `store_supply_items` ADD `productBrand` text;--> statement-breakpoint
ALTER TABLE `store_supply_items` ADD `productUnit` text;--> statement-breakpoint
ALTER TABLE `store_supply_items` ADD `variantName` text;--> statement-breakpoint
ALTER TABLE `store_supply_items` ADD `variantCode` text;--> statement-breakpoint
ALTER TABLE `store_supply_items` ADD `variantNetto` real;--> statement-breakpoint
ALTER TABLE `transaction_items` ADD `productName` text;--> statement-breakpoint
ALTER TABLE `transaction_items` ADD `productBarcode` text;--> statement-breakpoint
ALTER TABLE `transaction_items` ADD `productCategory` text;--> statement-breakpoint
ALTER TABLE `transaction_items` ADD `productBrand` text;--> statement-breakpoint
ALTER TABLE `transaction_items` ADD `productUnit` text;--> statement-breakpoint
ALTER TABLE `transaction_items` ADD `variantName` text;--> statement-breakpoint
ALTER TABLE `transaction_items` ADD `variantCode` text;--> statement-breakpoint
ALTER TABLE `transaction_items` ADD `variantNetto` real;--> statement-breakpoint
ALTER TABLE `transaction_items` ADD `itemNote` text;--> statement-breakpoint
ALTER TABLE `transaction_return_items` ADD `productName` text;--> statement-breakpoint
ALTER TABLE `transaction_return_items` ADD `productBarcode` text;--> statement-breakpoint
ALTER TABLE `transaction_return_items` ADD `productCategory` text;--> statement-breakpoint
ALTER TABLE `transaction_return_items` ADD `productBrand` text;--> statement-breakpoint
ALTER TABLE `transaction_return_items` ADD `productUnit` text;--> statement-breakpoint
ALTER TABLE `transaction_return_items` ADD `variantName` text;--> statement-breakpoint
ALTER TABLE `transaction_return_items` ADD `variantCode` text;--> statement-breakpoint
ALTER TABLE `transaction_return_items` ADD `variantNetto` real;--> statement-breakpoint
ALTER TABLE `transaction_return_items` ADD `purchasePrice` real DEFAULT 0;--> statement-breakpoint
ALTER TABLE `transaction_returns` ADD `customerPhone` text;--> statement-breakpoint
ALTER TABLE `transaction_returns` ADD `customerAddress` text;--> statement-breakpoint
ALTER TABLE `transaction_returns` ADD `employeeId` text;--> statement-breakpoint
ALTER TABLE `transaction_returns` ADD `employeeName` text;--> statement-breakpoint
ALTER TABLE `transaction_returns` ADD `originalTransactionLocalRefId` text;--> statement-breakpoint
ALTER TABLE `transactions` ADD `customerCode` text;--> statement-breakpoint
ALTER TABLE `transactions` ADD `customerName` text;--> statement-breakpoint
ALTER TABLE `transactions` ADD `customerPhone` text;--> statement-breakpoint
ALTER TABLE `transactions` ADD `customerAddress` text;--> statement-breakpoint
ALTER TABLE `transactions` ADD `employeeName` text;--> statement-breakpoint
ALTER TABLE `transactions` ADD `paymentTypeName` text;--> statement-breakpoint
ALTER TABLE `transactions` ADD `paymentTypeCommission` real DEFAULT 0;--> statement-breakpoint
ALTER TABLE `transactions` ADD `paymentTypeCommissionType` text DEFAULT 'PERCENTAGE';--> statement-breakpoint
ALTER TABLE `transactions` ADD `paymentTypeMinimalAmount` real DEFAULT 0;--> statement-breakpoint
ALTER TABLE `transactions` DROP COLUMN `paymentTypeId`;